#!/bin/bash

ONOS_CLI_DOCKER_NAME=${ONOS_CLI_DOCKER_NAME:-onos-cli}
ONOS_CLI_IMG=${ONOS_CLI_IMG:-davidlor/python-ssh}

docker run -d \
  --name $ONOS_CLI_DOCKER_NAME \
  --network host \
  $ONOS_CLI_IMG

